package ma.ewallet.account;

import java.math.BigDecimal;
import java.time.Instant;
import java.util.Objects;
import java.util.UUID;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.Table;
import jakarta.persistence.Version;

import ma.ewallet.common.error.InsufficientFundsException;
import ma.ewallet.money.CurrencyCode;
import ma.ewallet.user.AppUser;

/**
 * A wallet account (JPA entity mapped to the {@code accounts} table).
 *
 * <h2>Two sources of the balance</h2>
 * The <b>ledger entries</b> are the truth: the balance of an account is the
 * sum of its CREDIT lines minus the sum of its DEBIT lines. Recomputing that
 * sum on every read would be slow, so we also keep the result in the
 * {@code balance} column — a <b>cache</b>. The ledger service updates both in
 * the same transaction, and {@code /reconciliation} lets you check they agree.
 *
 * <h2>Optimistic locking ({@code @Version})</h2>
 * Problem ("lost update"): two transfers read balance = 100 at the same time,
 * both subtract 80, both write 20. 160 left the account but only 80 was taken!
 * <br>Solution: Hibernate adds a version number to the row and writes
 * {@code UPDATE accounts SET balance=?, version=version+1 WHERE id=? AND version=?}.
 * The second writer matches 0 rows (the version has changed), and Hibernate
 * throws {@code OptimisticLockException}. We then retry with fresh data
 * (see {@code OperationService}). "Optimistic" because we don't lock anything
 * upfront: we bet that conflicts are rare and detect them when they happen.
 *
 * <h2>SYSTEM accounts</h2>
 * They take part in <i>every</i> deposit and withdrawal. If they carried a
 * version, all deposits in the platform would conflict with each other. So
 * they keep no cached balance ({@code credit}/{@code debit} do nothing), are
 * never updated, and their position is always derived from the ledger.
 */
@Entity
@Table(name = "accounts")
public class Account {

    /** UUID generated by Hibernate on persist: not guessable, unlike 1, 2, 3... */
    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    private UUID id;

    /**
     * LAZY: the owner is only loaded from the database if we actually call
     * {@code getOwner()}. Null for SYSTEM accounts (enforced by a SQL CHECK).
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "owner_id")
    private AppUser owner;

    /** EnumType.STRING stores "USER"/"SYSTEM"; ORDINAL (0/1) would break if the enum were reordered. */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 10)
    private AccountType type;

    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 3)
    private CurrencyCode currency;

    /** NUMERIC(19,2) in PostgreSQL: exact decimal, like BigDecimal. */
    @Column(nullable = false, precision = 19, scale = 2)
    private BigDecimal balance;

    /**
     * Managed by Hibernate only — never set it yourself. A wrapper {@code Long}
     * (not {@code long}) so that "null" means "never saved": Spring Data then
     * knows to INSERT rather than UPDATE.
     */
    @Version
    private Long version;

    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt;

    /** JPA requires a no-arg constructor; {@code protected} so our own code cannot use it. */
    protected Account() {
    }

    /** Private: use the named factories below, which make the intent explicit. */
    private Account(AppUser owner, AccountType type, CurrencyCode currency) {
        this.owner = owner;
        this.type = type;
        this.currency = currency;
        this.balance = BigDecimal.ZERO.setScale(currency.scale()); // 0.00, not 0
        this.createdAt = Instant.now();
    }

    /** Opens a customer wallet. */
    public static Account openFor(AppUser owner, CurrencyCode currency) {
        return new Account(Objects.requireNonNull(owner, "owner"), AccountType.USER,
                Objects.requireNonNull(currency, "currency"));
    }

    /** Settlement account. In production they come from the Flyway migration; this is used by tests. */
    public static Account settlement(CurrencyCode currency) {
        return new Account(null, AccountType.SYSTEM, currency);
    }

    public boolean isSystem() {
        return type == AccountType.SYSTEM;
    }

    /**
     * Increases the balance. Public only because the ledger lives in another
     * package: <b>only {@code LedgerService} may call it</b>, always together
     * with a ledger entry — otherwise the cache and the ledger diverge.
     */
    public void credit(BigDecimal amount) {
        if (!isSystem()) {
            balance = balance.add(amount); // BigDecimal is immutable: add() returns a NEW object
        }
    }

    /**
     * Decreases the balance. The overdraft rule lives here, in the entity,
     * so that no caller can forget it ("rich domain model"). A SQL CHECK
     * constraint repeats the rule as a last line of defence.
     */
    public void debit(BigDecimal amount) {
        if (isSystem()) {
            return;
        }
        if (balance.compareTo(amount) < 0) {
            throw new InsufficientFundsException(id);
        }
        balance = balance.subtract(amount);
    }

    // --- Getters only: no setters, so state can only change through credit()/debit(). ---

    public UUID getId() {
        return id;
    }

    public AppUser getOwner() {
        return owner;
    }

    public AccountType getType() {
        return type;
    }

    public CurrencyCode getCurrency() {
        return currency;
    }

    public BigDecimal getBalance() {
        return balance;
    }

    public Long getVersion() {
        return version;
    }

    public Instant getCreatedAt() {
        return createdAt;
    }
}
